
#requirespackage 'PETSC_HAVE_VNV'

ALL: lib
SOURCEH   =
SOURCEC   = vnv.c vnv_petsc.c
DIRS      =
LOCDIR    = src/sys/vnv/
MANSEC    = Sys

include ${PETSC_DIR}/lib/petsc/conf/variables
include ${PETSC_DIR}/lib/petsc/conf/rules
include ${PETSC_DIR}/lib/petsc/conf/test
